version: '2'

services:
  app:
    build:
      context: .
    command: node index.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 1337:1337
  inspect:
    extends: app
    command:
      - node
      # Need the double quotes ""
      - "--inspect-brk=0.0.0.0"
      - index.js
    ports:
      - 9229:9229